Garduino/Controllers/api/CodeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Garduino.Data;
using Garduino.Data.Interfaces;
using Garduino.Hubs;
using Garduino.Models;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Controller = Microsoft.AspNetCore.Mvc.Controller;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.SignalR;
using Microsoft.AspNetCore.Sockets;
using Microsoft.EntityFrameworkCore;

namespace Garduino.Controllers.api
{
    [Authorize(AuthenticationSchemes = JwtBearerDefaults.AuthenticationScheme)]
    [Produces("application/json")]
    [Route("api/Code")]
    public class CodeController : Controller
    {
        private readonly ICodeRepository _repository;
        private readonly IDeviceRepository _deviceRepository;
        private readonly IHubContext<DeviceHub> _hubContext;
        //TODO: when transfering to ASP.NET just use _hubContext.Caller

        public CodeController(IDeviceRepository deviceRepository, ICodeRepository repository, 
            IHubContext<DeviceHub> hubContext
            )
        {
            _deviceRepository = deviceRepository;
            _repository = repository;
            _hubContext = hubContext;
        }

        // GET: api/Code
        [HttpGet("all/{deviceId}")]
        public async Task<IEnumerable<Code>> GetAll([FromRoute] Guid deviceId)
        {
            Device dev = await GetDeviceAsync(deviceId);
            if (dev == null) return null;
            var t = _repository.GetAll(dev);
            return t;
        }

        [HttpGet("active/{deviceId}")]
        public async Task<IEnumerable<Code>> GetActiveCode([FromRoute] Guid deviceId)
        {
            Device dev = await GetDeviceAsync(deviceId);
            if (dev == null) return null;
            return _repository.GetActive(dev);
        }

        [HttpGet("latest/{deviceId}")]
        public async Task<Code> GetLatestCode([FromRoute] Guid deviceId, bool invoke = true)
        {
            Device dev = await GetDeviceAsync(deviceId);
            if (dev == null) return null;
            Code code = _repository.GetLatest(dev);
            if (code == null) return null;
            if(invoke) {
                await _hubContext.Clients.Group(GetUserName()).InvokeAsync("codeFetched", dev.Name,
                string.IsNullOrWhiteSpace(code.ActionName) ? code.Action.ToString() : code.ActionName);
                
            }
            return code;
        }

        public class TimeDevice
        {
            public DateTime dateTime { get; set; }
            public Guid deviceId { get; set; }
        }

        [HttpPut("latest")]
        public async Task<IActionResult> CompleteCode([FromBody] TimeDevice timeDevice) //TODO: Complete & Fix.
        {
            if (!ModelState.IsValid) return BadRequest(ModelState);
            Code latest = await GetLatestCode(timeDevice.deviceId, false);
            if (latest == null) return NotFound();
            await _repository.CompleteAsync(latest, timeDevice.dateTime);
            await _hubContext.Clients.Group(GetUserName()).InvokeAsync("codeDone", latest.Device.Name,
                string.IsNullOrWhiteSpace(latest.ActionName) ? latest.Action.ToString() : latest.ActionName);
            return Ok();
        }

        // GET: api/Code/5
        [HttpGet("{id}")]
        public async Task<IActionResult> GetCode([FromRoute] Guid id)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            Code code = await _repository.GetAsync(id);

            if (code == null)
            {
                return NotFound();
            }

            return Ok(code);
        }

        // PUT: api/Code/5
        [HttpPut("{id}")]
        public async Task<IActionResult> PutCode([FromRoute] Guid id, [FromBody] Code code)
        {
            if (!ModelState.IsValid) return BadRequest(ModelState);

            if (!await _repository.UpdateAsync(id, code)) return NoContent();
            return Ok();
        }

        public class CodeDevice
        {
            public Code code { get; set; }
            public Guid deviceId { get; set; }
        }

        // POST: api/Code
        [HttpPost]
        public async Task<IActionResult> PostCode([FromBody] CodeDevice codeDevice)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            if (!await _repository.AddAsync(codeDevice.code, await GetDeviceAsync(codeDevice.deviceId))) return BadRequest();
            return Ok();
        }

        // DELETE: api/Code/5
        [HttpDelete("{id}")]
        public async Task<IActionResult> DeleteCode([FromRoute] Guid id)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            if (await _repository.DeleteAsync(id)) return Ok();
            return BadRequest();
        }

        [HttpDelete("deleteall")] //ONLY FOR DEVELOPMENT!
        public async Task<IActionResult> DeleteAll()
        {
            if (await _repository.DeleteAllAsync()) return Ok();
            return BadRequest();
        }

        private async Task<Guid> GetDeviceIdAsync(Guid codeId)
        {
            Code code = await _repository.GetAsync(codeId);
            Guid deviceId = code.Device.Id;
            return deviceId;
        }

        private async Task<Device> _GetDeviceAsync(Guid deviceId) => await _deviceRepository.GetAsync(deviceId);

        private async Task<Device> GetDeviceAsync(Guid? deviceId)
        {
            if (deviceId == null) return null;
            var device = await _GetDeviceAsync(deviceId.Value);
            return device ?? null;
        }

        private string GetUserName() => User.Identity.Name;
    }
}

Garduino/Controllers/api/DeviceController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Garduino.Data;
using Garduino.Data.Interfaces;
using Garduino.Hubs;
using Garduino.Models;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Controller = Microsoft.AspNetCore.Mvc.Controller;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.SignalR;
using Microsoft.EntityFrameworkCore;

namespace Garduino.Controllers.api
{
    [Authorize(AuthenticationSchemes = JwtBearerDefaults.AuthenticationScheme)]
    [Produces("application/json")]
    [Route("api/Device")]
    public class DeviceController : Controller
    {
        private readonly IDeviceRepository _repository;
        private readonly IUserRepository _userRepository;
        private readonly IHubContext<DeviceHub> _hubContext;
        private readonly UserManager<ApplicationUser> _userManager;

        public DeviceController(IDeviceRepository repository, IUserRepository userRepository,
            UserManager<ApplicationUser> userManager, IHubContext<DeviceHub> hubContext)
        {
            _repository = repository;
            _userRepository = userRepository;
            _userManager = userManager;
            _hubContext = hubContext;
        }

        // GET: api/Device
        [HttpGet]
        public async Task<IEnumerable<Device>> GetDevice()
        {
            return _repository.GetAll(await GetCurrentUserAsync());
        }

        [HttpGet("call/{name}")]
        public async Task<Guid?> Call(string name)
        {
            Device device = await _repository.GetAsync(name, await GetCurrentUserAsync());
            return device?.Id;
        }

        // GET: api/Device/5
        [HttpGet("{id}")]
        public async Task<IActionResult> GetDevice([FromRoute] Guid id)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            var device = await _repository.GetAsync(id);

            if (device == null)
            {
                return NotFound();
            }

            return Ok(device);
        }

        // PUT: api/Device/5
        [HttpPut("{id}")]
        public async Task<IActionResult> PutDevice([FromRoute] Guid id, [FromBody] Device device)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }
            Device dev = await _repository.GetAsync(id);
            if (id != dev.Id)
            {
                return BadRequest();
            }

            if (await _repository.UpdateAsync(id, device)) return Ok();
            return InternalServerError();
        }

        // POST: api/Device
        [HttpPost]
        public async Task<IActionResult> PostDevice([FromBody] Device device)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }
            if (await _repository.AddAsync(device, await GetCurrentUserAsync()))
            {
                return CreatedAtAction("GetDevice", new { id = device.Id }, device);
            }
            return InternalServerError();
        }

        // DELETE: api/Device/5
        [HttpDelete("{id}")]
        public async Task<IActionResult> DeleteDevice([FromRoute] Guid id)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            if (await _repository.DeleteAsync(id)) return Ok();
            return InternalServerError();
        }


        public class State
        {
            public int state { get; set; }
        }
        [HttpPut("{id}/status")]
        public async Task<IActionResult> PutState([FromRoute] Guid id, [FromBody] State state)
        {
            Device dev = await _repository.GetAsync(id);
            if (dev == null) return NotFound();
            if (state == null) return BadRequest();
            bool wasAlive = dev.Alive;
            dev.State = state.state;
            await _repository.UpdateAsync(id, dev);
            /*
            if (wasAlive ^ dev.Alive)
            {
                await _hubContext.Clients.Group(GetUserName()).InvokeAsync("updateState", dev.Name,
                    dev.Alive ? "has connected!" : "has died.");
            }*/
            return Ok();
        }

        [HttpGet("api/time")]
        public async Task<IActionResult> GetTime()
        {
            return Ok((await GetCurrentUserAsync()).GetUserTime());
        }

        private async Task<string> _GetCurrentUserIdAsync() =>
            (await _userManager.Users.FirstOrDefaultAsync(g => g.Email.Equals(User.FindFirst(ClaimTypes.NameIdentifier).Value)))?.Id;

        private async Task<User> GetCurrentUserAsync()
        {
            User user = await _userRepository.GetAsync(await _GetCurrentUserIdAsync());
            return user;
        }

        private IActionResult InternalServerError() => StatusCode(StatusCodes.Status500InternalServerError);

        private string GetUserName() => User.Identity.Name;
    }
}

Garduino/Views/Shared/Search.cshtml
@model string
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

<form asp-controller="Code" asp-action="@Model" asp-route-deviceId="@ViewData["deviceId"]" method="get">
    <input type="hidden" value="@ViewData["deviceId"]" name="deviceId" />
    <div class="input-group">
        <input type="text" class="form-control" placeholder="Search for..." name="searchString" value="@ViewData["searchInput"]">

    <span class="input-group-btn">
        <button class="btn btn-default" type="submit">Search</button>
    </span>
    </div>
</form>

Garduino/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>

    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Garduino</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap_custom.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap_custom.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.6.0/Chart.min.js" type="text/javascript"></script>
        <script src="https://code.jquery.com/jquery-1.11.3.min.js"></script>
    </environment>
</head>

<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                    <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Garduino</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Help">Help</a></li>
                    @if (!string.IsNullOrWhiteSpace(User.Identity.Name))
    {
                <li><a asp-area="" asp-controller="Device" asp-action="Index">My Devices</a></li>
}
                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - Garduino</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>